<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <Description>Update</Description>
    <Title>Update</Title>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWPF>true</UseWPF>
    <LangVersion>9</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="rcedit.exe" CopyToOutputDirectory="PreserveNewest" />
    <None Include="signtool.exe" CopyToOutputDirectory="PreserveNewest" />
    <None Include="update.com" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Burrow\Burrow.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
    <PackageReference Include="WpfAnimatedGif" Version="1.4.15.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.50.0" />
    <PackageReference Include="Spectre.Console" Version="0.50.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="StartupOption.cs" />
    <Compile Remove="AnimatedGifWindow.cs" />
    <Compile Remove="ProgressSource.cs" />
    <Compile Remove="Commands\ReleasifyCommand.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ILRepack" Version="2.0.34" PrivateAssets="All" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <PostBuildEvent>
      cd "$(TargetDir)"
      "$(NuGetPackageRoot)ilrepack\2.0.34\tools\ILRepack.exe" /internalize /out:$(TargetFileName).tmp $(TargetFileName) WpfAnimatedGif.dll Microsoft.Web.XmlTransform.dll Burrow.dll Mono.Cecil.dll ZstdSharp.dll ICSharpCode.SharpZipLib.dll Spectre.Console.dll Spectre.Console.Cli.dll
      del "$(TargetFileName)"
      ren "$(TargetFileName).tmp" "$(TargetFileName)"
    </PostBuildEvent>
  </PropertyGroup>

</Project>