<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <Description>SyncReleases</Description>
    <Title>SyncReleases</Title>
    <LangVersion>9</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Burrow\Burrow.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
    <PackageReference Include="Octokit" Version="0.10.0.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.50.0" />
    <PackageReference Include="Spectre.Console" Version="0.50.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-beta2-18618-05" ExcludeAssets="build;analyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.SourceLink.Common" Version="1.0.0-beta2-18618-05" ExcludeAssets="build;analyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Tasks.Git" Version="1.0.0-beta2-18618-05" ExcludeAssets="build;analyzers" PrivateAssets="all" />
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.4.240" ExcludeAssets="build;analyzers" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ILRepack" Version="1.26.0" PrivateAssets="All" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <PostBuildEvent>
      cd "$(TargetDir)"
      "$(NuGetPackageRoot)ilrepack\1.26.0\tools\ILRepack.exe" /internalize /out:$(TargetFileName).tmp $(TargetFileName) Microsoft.Web.XmlTransform.dll Burrow.dll Octokit.dll ZstdSharp.dll ICSharpCode.SharpZipLib.dll Spectre.Console.dll Spectre.Console.Cli.dll
      del "$(TargetFileName)"
      ren "$(TargetFileName).tmp" "$(TargetFileName)"
    </PostBuildEvent>
  </PropertyGroup>

</Project>