name: Build Burrow

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Burrow
        shell: cmd
        run: ./src/build_official.cmd

      - name: Test Burrow
        shell: cmd
        run: ./test/test_official.cmd

      - name: Save build
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/artifacts/
