name: Build Burrow

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Build Burrow
        shell: cmd
        run: .\src\build_official.cmd

      - name: Test Burrow
        shell: cmd
        run: .\test\test_official.cmd

      - name: Test CLI Tools
        run: |
          dotnet test test/Update.Cli.Tests/Update.Cli.Tests.csproj --verbosity normal
          dotnet test test/SyncReleases.Cli.Tests/SyncReleases.Cli.Tests.csproj --verbosity normal

      - name: Save build
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/artifacts/
